apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullstack-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.telegram: "199643258"
    notifications.argoproj.io/subscribe.on-sync-failed.telegram: "199643258"
    notifications.argoproj.io/subscribe.on-degraded.telegram: "199643258"
spec:
  project: default
  source:
    repoURL: https://github.com/satriavilly/fullstack-app-dummy-k8s-config.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
