name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code (with submodules)
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set short SHA as image tag
      id: vars
      run: echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile.backend
        push: true
        tags: |
          satriav/myapp-backend:${{ steps.vars.outputs.TAG }}
          satriav/myapp-backend:latest

    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile.frontend
        push: true
        build-args: |
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
        tags: |
          satriav/myapp-frontend:${{ steps.vars.outputs.TAG }}
          satriav/myapp-frontend:latest

    - name: Update image tags in k8s-config repo
      run: |
        git clone https://x-access-token:${{ secrets.CONFIG_REPO_TOKEN }}@github.com/satriavilly/fullstack-app-dummy-k8s-config.git
        cd fullstack-app-dummy-k8s-config

        sed -i "s|satriav/myapp-backend:.*|satriav/myapp-backend:${{ steps.vars.outputs.TAG }}|" backend.yaml
        sed -i "s|satriav/myapp-frontend:.*|satriav/myapp-frontend:${{ steps.vars.outputs.TAG }}|" frontend.yaml

        git config user.email "github-actions@github.com"
        git config user.name "GitHub Actions"
        git add backend.yaml frontend.yaml
        git commit -m "ci: update image tags to ${{ steps.vars.outputs.TAG }}"
        git push
